



save('variables_ADSEE_I_hybrid.mat', 'A', 'MTOW', 'OEW', 'S', 'V_cruise', 'W4W5',...
    'W_fuel_used', 'tr', 'sweep_LE', 'sweep_TE', "sweep_2c",'sweep_4c',...
    "h", "S_h", "S_v", "b", "N", "W_fuel_total", "CL_max", "CL_to", "e",...
    "tc", "cl_cruise", "cr", "ct", "b", "V_stall",...
    "h", "S_h", "S_v", "b", "N", "W_fuel_total", "M_cruise", "MAC",...
    "A_h", "A_v", "b_h", "b_v")


save('variables_ADSEE_I_electric.mat', 'A', 'MTOW', 'OEW', 'S', 'V_cruise', 'W4W5',...
    'W_fuel_used', 'tr', 'sweep_LE', 'sweep_TE', "sweep_2c",'sweep_4c',...
    "h", "S_h", "S_v", "b", "N", "W_fuel_total", "CL_max", "CL_to", "e",...
    "tc", "cl_cruise", "cr", "ct", "b", "V_stall",...
    "h", "S_h", "S_v", "b", "N", "W_fuel_total", "M_cruise", "MAC",...
    "A_h", "A_v", "b_h", "b_v")